branches: [{ name: main, prerelease: true }]
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/github", { successComment: false }]
