#!/usr/bin/env python3

import json
import numpy
import re
import semver
import subprocess

MAX_WORKERS = 4

result = subprocess.run(
  ["env", "NIXPKGS_ALLOW_UNFREE=1", "nix", "build", "--impure", "--dry-run", "#all"],
  capture_output=True,
  text=True
)

versions = []

for line in result.stderr.splitlines():
  if "warning" in line or "will be built:" in line:
    continue

  matches = re.findall("terraform-([0-9]+\\.[0-9]+\\.[0-9]+)\\.drv", line)

  if not len(matches) > 0:
    break

  versions.append(semver.VersionInfo.parse(matches[0]))

if len(versions) > 10:
  versions.sort()
  installables = list(map(lambda version: f".#\\\"{version}\\\"", versions))
  grouped_installables = numpy.array_split(installables, MAX_WORKERS)
  installables_per_worker = list(map(lambda installables: " ".join(installables), grouped_installables))
  print(json.dumps(installables_per_worker))
else:
  print(json.dumps([".#all"]))
