---
name: Update versions

on: push
# on:
#     schedule:
#         - cron: "5 * * * *"

concurrency:
    group: update
    cancel-in-progress: true
    
jobs:
    check:
        permissions:
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install Nix
          uses: DeterminateSystems/nix-installer-action@v6
        - name: Install tools via Nix
          run: nix develop --impure --check
        - name: Check code format
          run: nix develop --impure --command python3 update-versions.py vendor-hash.nix
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Create Pull Request
          id: create-pull-request
          uses: peter-evans/create-pull-request@v5
          with:
            commit-message: Update Terraform versions
            title: Update Terraform versions
            body: |
                Automatically created pull-request to update Terraform versions.
            
                This is the result of running:
    
                ```
                env GITHUB_TOKEN=<my-token> nix develop --impure --command python3 update-versions.py vendor-hash.nix
                ```
            delete-branch: true